config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :tags, only: [:show]
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts do
      collection do
        get 'poisk'
      end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
   extend FriendlyId
    friendly_id :name, use: :slugged

    def should_generate_new_friendly_id?
      name_changed?
    end

    def normalize_friendly_id(string)
      string.to_slug.normalize.to_s
    end
  has_many :posts

  validates :name, presence: true

  has_ancestry
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
    friendly_id :title, use: :slugged

    def should_generate_new_friendly_id?
      title_changed?
    end

    def normalize_friendly_id(string)
      string.to_slug.normalize.to_s
    end
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :category
  mount_uploader :image, ImageUploader
  validates :title, :body, presence: true

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  searchable do
    text :title, :body
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
   
  extend FriendlyId
    friendly_id :name, use: :slugged

    def should_generate_new_friendly_id?
      name_changed?
    end

    def normalize_friendly_id(string)
      string.to_slug.normalize.to_s
    end

  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 2)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
    
  end

  def poisk
     @query = Post.search do
        fulltext(params[:search])
    end
    @posts = @query.results
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create 
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :category_id, :all_tags)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
   
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_breadcrumb(category)
    result = []
    category.ancestors.each do |ancestor|
      result << content_tag(:li, class: "breadcrumb-item") do
        link_to(ancestor.name, ancestor)
      end
    end
    result << content_tag(:li, category.name, class: "breadcrumb-item active")
    result.join('').html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    

  -if controller.action_name == 'edit' 
    .form-inputs
      = f.label :parent_id 
      = f.collection_select :parent_id, Category.where("id != #{@category.id}").order(:name), :id, :name, { include_blank: true } 


  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table
  thead
    tr
      th Name
      th Категория родитель
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td = category.parent.name if category.parent.present?
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
= render 'shared/breadcrumb', category: @category

h1= @category.name

section#posts
= render @posts

= will_paginate(@posts, renderer: BootstrapPagination::Rails)

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
            <a class="nav-link" href="<%= root_path %>">Все статьи</a>
          </li>
        <li><a href="#">Контакты</a></li>
         </li>
          
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Действие</a></li>
            <li><a href="#">Другое действие</a></li>
            <li><a href="#">Что-то еще</a></li>
            <li class="divider"></li>
            <li><a href="#">Отдельная ссылка</a></li>
            <li class="divider"></li>
            <li><a href="#">Еще одна отдельная ссылка</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search" action='<%= poisk_posts_path %>'>
        <div class="form-group">
           <%= text_field_tag :search, params[:search], action: 'poisk'  %>
        </div>
        <%= submit_tag "Отправить",:name => nil, :class => "button postfix" %>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= new_post_path %>">Новая статья</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Действие</a></li>
            <li><a href="#">Другое действие</a></li>
            <li><a href="#">Что-то еще</a></li>
            <li class="divider"></li>
            <li><a href="#">Отдельная ссылка</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

            

<nav class="nav">
 <ul class="nav nav-tabs">
 <% Category.order(:name).roots.each do |category| %>
        <li <%= 'active' if current_page?(category_path(category)) %>">
              <%= link_to category.name, category, class: 'nav-link' %>
               </li>
          <% end %>
               
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogpost</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container-fluid">

  <%= render 'layouts/navbar' %>
<div class="container main">
<div class="row">

        <div class="col-md-9">
          <%= yield %>
        </div>

        <div class="col-md-3">
              <%= render 'shared/submenu' %>

            <div class="tag_cloud">
              <h2>Теги</h2>
              <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
                <%= link_to tag.name, tag_path(tag.name), class: css_class %>
              <% end %>
           </div>
        </div>

    </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.slim
= simple_form_for(@post, html: { multipart: true }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}
    = f.input :image
    = f.input :all_tags 
    = f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }

  .form-actions
    = f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary'
    | &nbsp; &nbsp; &nbsp;
    = link_to t('common.back'), :back, class: 'btn btn-default'

app/views/posts/_post.html.slim
article.post
  section.post-head
    h2= link_to post.title, post 
    small
      time='  post.created_at.to_date.strftime("%d %B, %Y")
      - if post.category.present? 
        ' |
        =' link_to post.category.name, post.category
      ' | 
      =' link_to 'Изменить', edit_post_path(post)
      ' | 
      = link_to 'Удалить', post, method: :delete, data: { confirm: "Удалить насовсем?"}
  section.post-summary.clearfix
    = image_tag(post.image_url(:thumb), class: 'img-thumbnail thumb' ) if post.image?
    = strip_tags(raw(post.body).truncate(580))

  section.footer-summary
    = raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary' }.join(' ')

app/views/posts/edit.html.slim
h1 = t('.title')

== render 'form'

 

app/views/posts/index.html.slim
= render @posts


= will_paginate(@posts, renderer: BootstrapPagination::Rails)
  

app/views/posts/new.html.slim
h1 = t('.title') 

== render 'form'

 

app/views/posts/poisk.html.slim
- @posts.each do |post|

  article.post
    section.post-head
      h2= link_to post.title, post 
      small
        time='  post.created_at.to_date.strftime("%d %B, %Y")
        ' | 
        =' link_to 'Изменить', edit_post_path(post)
        ' | 
        = link_to 'Удалить', post, method: :delete, data: { confirm: "Удалить насовсем?"}
    section.post-summary.clearfix
      = image_tag(post.image_url(:thumb), class: 'img-thumbnail thumb' ) if post.image?
      = strip_tags(raw(post.body).truncate(580))

    section.footer-summary
      = raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary' }.join(' ')

app/views/posts/show.html.slim
article.post
  section.post-head
    h1= @post.title 
    small
      time='  @post.created_at.to_date.strftime("%d %B, %Y")
      - if @post.category.present? 
        ' |
        =' link_to @post.category.name, @post.category
      ' | 
      =' link_to 'Изменить', edit_post_path(@post)
      ' | 
      = link_to 'Удалить', @post, method: :delete, data: { confirm: "Удалить насовсем?"}
  section.post-body.clearfix
    = image_tag(@post.image_url(:large), class: 'img-show' ) if @post.image?
    = raw(@post.body.html_safe)

     

app/views/shared/_breadcrumb.html.erb
<% if category.present? && category.parent %>
  <ol class="breadcrumb">
    <%= build_breadcrumb(category) %>
  </ol>
<% end %>

app/views/shared/_submenu.html.erb
<div class="submenu">
  <h2>Категории</h2>
  <ul class="nav nav-pills nav-stacked">
    <% Category.roots.each do |category| %>
      <li class="nav-item">
        <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
        <%= render 'shared/submenu_categories', categories: category.root.descendants.arrange %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_submenu_categories.html.erb
<ul class="nav nav-pills nav-stacked nested_nav">
  <% categories.each do |category, children| %>
    <li>
      <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
      <%= render 'shared/submenu_categories', categories: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/tags/_form.html.slim
= simple_form_for(@tag) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/tags/edit.html.slim
h1 Editing tag

== render 'form'

= link_to 'Show', @tag
'|
= link_to 'Back', tags_path

app/views/tags/index.html.slim
h1 Listing tags

table
  thead
    tr
      th Name
      th Slug
      th
      th
      th

  tbody
    - @tags.each do |tag|
      tr
        td = tag.name
        td = tag.slug
        td = link_to 'Show', tag
        td = link_to 'Edit', edit_tag_path(tag)
        td = link_to 'Destroy', tag, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.slim
h1 New tag

== render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.slim
h1= @tag.name

- if @tag.posts.empty? 
  h2 Статей нет
-else
  = render @tag.posts